services:
  postgres:
    build:
      context: .
      dockerfile: postgres.dockerfile
    image: "postgres-image-for-keystracker"
    container_name: ${PG_CONTAINER_NAME}
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: ${PGDATA}
    volumes:
      - dbkeystracker:/data/postgres_keystracker
    ports:
      - "5432:5432"
    restart: always
  redis:
    image: redis:7.0.12-alpine
    container_name: ${REDIS_CONTAINER_NAME}
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - dbkeystracker:/data/redis_keystracker

volumes:
  dbkeystracker:
    external: true
