services:
  postgres:
    build:
      context: .
      dockerfile: postgres.dockerfile
    image: "postgres-image-for-keystracker"
    container_name: ${PG_CONTAINER_NAME}
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: ${PGDATA}
    volumes:
      - dbkeystracker:/data/postgres_keystracker
    ports:
      - "5432:5432"
    restart: always
volumes:
  dbkeystracker:
    external: true
